syntax = "proto3";

option go_package = "golang.garena.com/vodka/backend/internal/protocol/pbcommon";

package protocommon;

message Empty {
}

enum Error {
  NONE = 0;
  SERVER_INTERNAL_EXCEPTION = 100;

  APP_KEY_IS_NOT_VALID = 201;
  ACCOUNT_ID_NOT_VALID = 202;

  CHANNEL_IS_FULL = 301;
}


message EProtocol {
  enum Proto {
    Proto_NONE = 0;
    INIT = 1;
    ACCOUNT = 11;
    HEARTBEAT = 2;
    SIGNALING = 40;
  }

  enum ProtoSize {
    ProtoSize_NONE = 0;
    MAXPACKETSIZE = 20480;
    MAXMTPPACKETSIZE = 10240; //1024*10
    MAXUGCDEBUGPACKETSIZE = 1048576; //1024*1024
  }
}

message ProtoReq {
  uint32 cmd = 1;
  bytes data = 2;
}

message MessageNotify {
  uint64 account_id = 1;
  uint32 protocol = 2; //参见EProtocol.Proto
  uint32 ret = 3;
  uint32 cmd = 4;
  bytes content = 5;
}

message ClaimReq {
  string app_key = 1;
  string account_id = 2;
  string region = 3;
  string country_code = 4;
  string sdk_platform = 5;
}

message ClaimFields {
  string app_key = 1;
  string account_id = 2;
  string region = 3;
  string country_code = 4;
  string sdk_platform = 5;
}

message CustomizedInfo {
  string app_key = 1;
  string sdk_platform = 2;
}

//voiceService
message EVoiceService {
  enum SDP {
    SDP_NONE = 0;
    // SDPTypeOffer indicates that a description MUST be treated as an SDP offer.
    SDP_OFFER = 1;
    // SDPTypePranswer indicates that a description MUST be treated as an
    // SDP answer, but not a final answer. A description used as an SDP
    // pranswer may be applied as a response to an SDP offer, or an update to
    // a previously sent SDP pranswer.
    SDP_PRANSWER = 2;
    // SDPTypeAnswer indicates that a description MUST be treated as an SDP
    // final answer, and the offer-answer exchange MUST be considered complete.
    // A description used as an SDP answer may be applied as a response to an
    // SDP offer or as an update to a previously sent SDP pranswer.
    SDP_ANSWER = 3;
    // SDPTypeRollback indicates that a description MUST be treated as
    // canceling the current SDP negotiation and moving the SDP offer and
    // answer back to what it was in the previous stable state. Note the
    // local or remote SDP descriptions in the previous stable state could be
    // null if there has not yet been a successful offer-answer negotiation.
    SDP_ROLLBACK = 4;
  }

  enum ServerStatus {
    ServerStatus_NONE = 0;
    ServerStatus_RUNNING = 1;
    ServerStatus_SOFTCLOSED = 2;
    ServerStatus_DOWN = 3;
  }

  enum LeaveReason {
    LeaveReason_NORMAL = 0;
    LeaveReason_OFFLINE = 1;
    LeaveReason_SELF = 2;
    LeaveReason_OFFLINE_UDP = 3;
    LeaveReason_MULTI_JOIN = 4;
  }

  enum ChannelType {
    ChannelType_MCU = 0;
    ChannelType_SFU = 1;
  }
}

message RTCSessionDescription {
  EVoiceService.SDP type = 1;
  string sdp = 2;
  bool sdp_is_compressed = 3;
}

message VoiceServiceInfo {
  string app_key = 1;
  string region = 2;
  string idc = 3;
  string address = 4;
  StatusInfo status_info = 5;
  LoadInfo load_info = 6;
}

message StatusInfo {
  EVoiceService.ServerStatus status = 1;
  uint32 status_update_time = 2;
}

message LoadInfo {
  uint32 channel_max_load_count = 1;
  repeated ChannelInfo channel_cur_load_infos = 2;
  uint32 per_channel_max_account = 3;
  GPoolInfo pool_info = 4;
}

message GPoolInfo {
  uint32 cap = 1;
  uint32 waiting = 2;
  uint32 running = 3;
}

message ChannelInfo {
  string channel_id = 1;
  uint32 joined_account_count = 2;
  uint32 connected_account_count = 3;
  uint32 microphone_open_account_count = 4;
}

message AppInfo {
  string app_key = 1;
  string game_code = 2;
  AppExtInfo ext_info = 3;
}

message AppExtInfo {
  repeated AppEnvInfo env_infos = 1;
}

message AppEnvInfo {
  string env = 1;
  string secret = 2;
  int64 create_time = 3;
}
message ICECandidateInit {
  string candidate = 1;
  string sdp_mid = 2;
  uint32 sdp_mLine_index = 3;
  string username_fragment = 4;
}

//sdk
message SDKParams {
  SDKTcpParams tcp_params = 1;
  SDKReportParams report_params = 2;
  SDKEventParams event_params = 3;
}

message SDKReportParams {
  string region = 1;
  bool enable = 2;
  repeated string address_list = 3;
}

message SDKEventParams {
  string region = 1;
  bool enable = 2;
  repeated string address_list = 3;
  uint32 audio_quality_upload_internal_ms = 4;
}

message SDKTcpParams {
  uint32 timeout_ms = 1;
  int32 retries = 2;// 0 means no retried; -1 means retried forever; others means retried times.
  uint32 retry_delay_ms = 3;
  uint32 max_retry_delay_ms = 4;
}

message SDK {
    enum EParamFilterType{
        EParamFilterType_NONE = 0;//解释 参数类型 取值示例 通用配置
        EParamFilterType_REGION = 1;//区域 EValueType_STRING SG/... ALL
        EParamFilterType_SYSTEM_VERSION = 2;//手机系统版本 EValueType_STRING 12.0.1/... 0.0.0
        EParamFilterType_CPU_ARC = 3;//CPU架构 EValueType_STRING x64/x86/... 空字符串
        EParamFilterType_CPU_CHIP = 4;//CPU型号 EValueType_STRING  Intel i7/ARM Cortex/... 空字符串
        EParamFilterType_PHONE_COMPANY = 5;//手机厂商 EValueType_STRING 小米/红米/... 空字符串
        EParamFilterType_PHONE_MODEL = 6;//手机型号 EValueType_STRING iphone17Pro/huawei P50/... 空字符串
        EParamFilterType_DEVICE_ID = 7;//设备ID EValueType_STRING fsfdsc/... 空字符串
        EParamFilterType_SDK_VERSION = 8;//SDK的版本号 EValueType_STRING 0.1.1/0.2.0/... 0.0.0
        EParamFilterType_SDK_PLATFORM = 9;//SDK平台 EValueType_STRING android/ios 空字符串
        EParamFilterType_ACCOUNT_ID = 10;//账号ID EValueType_STRING sds12743 空字符串
        EParamFilterType_APP_KEY = 11;//AppKey EValueType_STRING xxxxxxxx 空字符串
        EParamFilterType_GRAPHIC_QUALITY = 12;//画质枚举 EValueType_INT 1/2/3/4 0
        EParamFilterType_CPU_COUNT = 13;//CPU个数 EValueType_INT 1/2/3/4 0
        EParamFilterType_MEMORY_CAPACITY = 14;//内存(G) EValueType_INT 1/2/3/4/16 0
    }

  message ParamFilterValue {
    EParamFilterType param_filter_type = 1;
    string value = 2;
  }

  enum EValueType {
    EValueType_INT = 0;
    EValueType_BOOL = 1;
    EValueType_STRING = 2;
    EValueType_FLOAT = 3;
  }

  enum EConditionType {
    EConditionType_EQUAL = 0;
    EConditionType_GREATER_THAN = 1;
    EConditionType_LESS_THAN = 2;
    EConditionType_GREATER_THAN_OR_EQUAL = 3;
    EConditionType_LESS_THAN_OR_EQUAL = 4;
  }

  enum EStatus {
    Status_DISABLE = 0;
    Status_WAIT_PUBLISH = 1;
    Status_PUBLISH_ED = 2;
  }

  message ParamDefine {
    uint64 id = 1;
    string name = 2;
    string desc = 3;
    EValueType value_type = 4;
    string value_desc = 5;
  }

  message ParamFilterDefine {
    uint64 id = 1;
    EParamFilterType param_filter_type = 2;
    EValueType value_type = 3;
    EConditionType condition_type = 4;
    string value = 5;
    string desc = 6;
  }

  message Param {
    uint64 id = 1;
    uint32 weight = 2;
    EStatus status = 3;
    ParamDefine param_define = 4;
    string value = 5;
    AppInfo app_info = 6;
    ParamExt param_ext = 7;
    string desc = 8;
  }

  message ParamExt {
    repeated ParamFilterDefine filter_params = 1;
  }

  message Value {
    string name = 1;
    EValueType value_type = 2;
    string value = 3;
  }
}

message VoiceAccountInfo{
  string account_id = 1;
  string platform = 2;
}


