name: Extract Specific Files (.so & .proto) to Repo

on:
  workflow_dispatch:

jobs:
  extract-specific-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download APK using cURL
        run: |
          curl "https://dw.uptodown.net/dwn/j_N6FMAzG6kPZEfp8nlNNRJplfDvIBz-msgrx2NrUiJZO5_-BYElqccZLwpwJLKkCv9Vm08egj4P7bHxgftja8ZuhxJ__ScQ_6Z7J7dX8dYRxNZ5orZMeeXVzZs_9IrD/zPmmqkeusEQTNxF_-wpNBqit16FxDoV1-ERXdop2NjIQPBeCy73MTxD38tgzGY2TgfUo3uSDrCnLxh33DThx-UQvf05kII9iu4kO4Xick7IYXnb_vxdoK5S6xYBum8Fg/A0MT9uMEpmxsXij7XQqXTdm7c37hYGcOe4pTE9sMwAvLE7kkp60Z1C2Z0SSfdzEWJjhBasfWF3uBZYyXMnq_6atS6zfiCZLQq24N4BtJHIQ=/free-fire-1-132-1.apk" \
            -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" \
            -H "accept-language: en-US,en;q=0.9" \
            -H "dnt: 1" \
            -H "priority: u=0, i" \
            -H "referer: https://free-fire-battlegrounds.id.uptodown.com/" \
            -H 'sec-ch-ua: "Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"' \
            -H "sec-ch-ua-mobile: ?0" \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H "sec-fetch-dest: document" \
            -H "sec-fetch-mode: navigate" \
            -H "sec-fetch-site: cross-site" \
            -H "sec-fetch-user: ?1" \
            -H "upgrade-insecure-requests: 1" \
            -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36" \
            -o "free-fire-1-132-1.apk"

      - name: Install Unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Unzip and Filter Target Files
        run: |
          # Ekstrak isi APK ke folder sementara
          unzip -q free-fire-1-132-1.apk -d temp_apk

          # Buat struktur folder tujuan di repo
          mkdir -p extracted_files/native_libs
          mkdir -p extracted_files/proto_schemas

          # 1. Ambil HANYA file .so dari folder lib/
          if [ -d "temp_apk/lib" ]; then
            cp -r temp_apk/lib/* extracted_files/native_libs/
          fi

          # 2. Cari dan ambil HANYA file .proto
          find temp_apk/ -name "*.proto" -exec cp {} extracted_files/proto_schemas/ \;

          # Hapus folder sementara agar hemat ruang disk
          rm -rf temp_apk free-fire-1-132-1.apk

      - name: Commit and Push Target Files to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add extracted_files/
          
          if git diff --staged --quiet; then
            echo "Tidak ada file baru yang ditemukan."
          else
            git commit -m "Add extracted .so and .proto files from APK"
            git push
          fi
